name: NPM

on:
  push:
    paths:
      - 'package.json'
      - '.github/workflows/publish.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "npm"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install

      - run: mkdir dist

      - name: Build
        run: npx rollup -c

      - name: Minify
        run: npx terser dist/jssc.js -c -m "reserved=['compress','decompress','JSSC','jssc']" --format "ascii_only=true" -o index.min.js

      - run: cp dist/jssc.js index.js
      - run: bash src/prefix.sh

      - name: Run tests
        run: npm test

      - name: Publish
        run: npm publish --access public
